[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
# watch = { ignore_pattern = "static/*" }

[tasks.build-release]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]

[tasks.serve]
command = "http-server"
args = ["./static/", "-p", "3000", "-a", "127.0.0.1", "-c-1"]
